[system]
serverId = "356414885292277771"
color = "#1793d0"

[localization]
permissionDenied = "You do not have permission to use this command."
# results in <name> says <message>
redirectedMessage = "says"
messageDeleted = "Your message was deleted because it contained a banned word or phrase."

[[command]]
trigger = "!ping"
response = "pong"

[[command]]
trigger = "somewhere"
response = "found it"
matchType = "CONTAINS"

[[command]]
trigger = "A.+B"
response = "regex matched"
matchType = "REGEX"

[[command]]
trigger = "answer me"
# this will @mention the user who triggered the command,
# i.e. “@author there you go”
response = "@@ there you go"

[[command]]
trigger = "delet this"
[command.action]
delete = true

[[command]]
trigger = "!restricted"
response = "access granted"
[command.permissions]
hasOneOf = [
    452034011393425409,
    446668543816106004
]

[[command]]
trigger = "!almostUnrestricted"
response = "access granted"
[command.permissions]
hasNoneOf = [452034011393425409]



# redirect every message that starts with !redirect to channel 555097559023222825
[[command]]
trigger = "!redirect"
response = "redirected"
[command.action.redirect]
target = 555097559023222825

# the same, but without the original username
[[command]]
trigger = "!anonRedirect"
response = "redirected"
[command.action.redirect]
target = 555097559023222825
anonymous = true
