[system]
serverId = "356414885292277771"
admins = [
    "137780880344088576"
]

[[commands]]
trigger = "!ping"
response = "pong"

[[commands]]
trigger = "somewhere"
response = "found it"
matchType = "CONTAINS"