[system]
serverId = "356414885292277771"
color = "#1793d0"

[localization]
# empty string to disable the message
permissionDenied = "You do not have permission to use this command."
# results in <name> says <message>
redirectedMessage = "says"
messageDeleted = "Your message was deleted because it contained a banned word or phrase."

# If this is enabled, every new user will receive a welcome message.
# If the user has disabled their DMs, the fallbackMessage will be sent in the fallbackChannel instead.
# If no fallback channel or message is specified, no fallback will be sent.
[feature.welcome]
enabled = true
# enable the !welcome command which will print the welcome embed
command = true
fallbackChannel = "555097559023222825"
fallbackMessage = "@@ I would like to greet you, but I can’t. :("
# This is a list of pairs where the key is the title and the value the content of the paragraph.
# Do not use empty strings to get empty headings or paragraphs. The discord API rejects those.
[feature.welcome.content]
"Welcome to the Server" = "This is the content of the first paragraph"
"Second paragraph heading" = "Second paragraph content"

# allow the bot owner to get debug stats
[feature.debug]
enabled = true

[[command]]
trigger = "!ping"
response = "pong"

[[command]]
trigger = "somewhere"
response = "found it"
matchType = "CONTAINS"

[[command]]
trigger = "A.+B"
response = "regex matched"
matchType = "REGEX"

[[command]]
trigger = "!embed"
embed = { "some embed heading" = "your embed content" }

[[command]]
trigger = "answer me"
# this will @mention the user who triggered the command,
# i.e. “@author there you go”
response = "@@ there you go"

[[command]]
trigger = "delet this"
[command.action]
delete = true

[[command]]
trigger = "!restricted"
response = "access granted"
[command.permissions]
hasOneOf = [
    "452034011393425409",
    "446668543816106004"
]

[[command]]
trigger = "!almostUnrestricted"
response = "access granted"
[command.permissions]
hasNoneOf = ["452034011393425409"]

[[command]]
trigger = "!private"
response = "some long response that you don’t want in public channels"
[command.permissions]
onlyDM = true

# redirect every message that starts with !redirect to channel 555097559023222825
[[command]]
trigger = "!redirect"
response = "redirected"
[command.action.redirect]
target = "testchannel"

# the same, but without the original username
[[command]]
trigger = "!anonRedirect"
response = "redirected"
[command.action.redirect]
target = "555097559023222825"
anonymous = true
