[system]
serverId = "356414885292277771"
color = "#1793d0"

[localization]
permissionDenied = "You do not have permission to use this command."
# results in <name> says <message>
redirectedMessage = "says"

[[commands]]
trigger = "!ping"
response = "pong"

[[commands]]
trigger = "somewhere"
response = "found it"
matchType = "CONTAINS"

[[commands]]
trigger = "A.+B"
response = "regex matched"
matchType = "REGEX"

[[commands]]
trigger = "answer me"
# this will @mention the user who triggered the command,
# i.e. “@author there you go”
response = "@@ there you go"

[[commands]]
trigger = "delet this"
actions = { delete = true }

[[commands]]
trigger = "!restricted"
response = "access granted"
# a user needs *one of* these roles to trigger the command
neededRoles = [
    452034011393425409,
    446668543816106004
]

# redirect every message that starts with !redirect to channel 555097559023222825
[[commands]]
trigger = "!redirect"
response = "redirected"
actions = { redirect = { target = 555097559023222825 } }

# the same, but without the original username
[[commands]]
trigger = "!anonRedirect"
response = "redirected"
actions = { redirect = {target = 555097559023222825, anonymous = true } }
