[system]
serverId = "356414885292277771"
admins = [
    "137780880344088576"
]

[[commands]]
trigger = "!ping"
response = "pong"

[[commands]]
trigger = "somewhere"
response = "found it"
matchType = "CONTAINS"

[[commands]]
trigger = "A.+B"
response = "regex matched"
matchType = "REGEX"

[[commands]]
trigger = "answer me"
# this will @mention the user who triggered the command,
# i.e. “@author there you go”
response = "@@ there you go"

[[commands]]
trigger = "delet this"
deleteMessage = true

[[commands]]
trigger = "^[^`]*([()|DoOvVcC][-=^']?;|;[-=^']?[()|DoOpPvVcC3]|:wink:|😉)[^`]*$"
response = "@@ Oboe!"
matchType = "REGEX"
deleteMessage = true